name: "CI/CD pipeline"

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 #Descarga el código del repositorio en el runner

      - name: Configurar Infraestructura
        uses: ./.github/InfraConfig            #Ejecuta la action custom de InfraConfig

      - name: Build
        run: echo "Building the project..."   #Ejecuta un echo en el build
      
      - name: Deploy
        run: echo "Deploying the project..."  #Ejecuta un echo en el deploy
      
      - name: Test
        run: echo "Testing the project..."    #Ejecuta un echo en el test